blank_issues_enabled: true
contact_links:
 - name: Feature Ideas & Questions
   url: https://github.com/SimonSaysGiveMeSmile/SoA-Prod/issues/new
   about: Open an issue to share a feature idea or ask a question about Son of Anton.
